CREATE USER IF NOT EXISTS 'BistroFDI'@'%' IDENTIFIED BY 'BistroFDI';
GRANT ALL PRIVILEGES ON `BistroFDI`.* TO 'BistroFDI'@'%';

CREATE USER IF NOT EXISTS 'BistroFDI'@'localhost' IDENTIFIED BY 'BistroFDI';
GRANT ALL PRIVILEGES ON `BistroFDI`.* TO 'BistroFDI'@'localhost';

FLUSH PRIVILEGES;