CREATE USER IF NOT EXISTS 'prAW'@'localhost' IDENTIFIED BY 'practicaAW1234';
GRANT ALL PRIVILEGES ON `prAW`.* TO 'prAW'@'localhost';

CREATE USER IF NOT EXISTS 'prAW'@'%' IDENTIFIED BY 'practicaAW1234';
GRANT ALL PRIVILEGES ON `prAW`.* TO 'prAW'@'%';

FLUSH PRIVILEGES;